### ISSUE TITLE
document instantiating the database

### ISSUE THREAD

**Issue by BrianHGrant** [hackoregon/crash-data-wrangling#2]

**Comment by znmeb** [comment]
I've build a new `docker-compose.yml` / `Dockerfile` setup to bring the database up in a network. See <https://github.com/hackoregon/crash-data-wrangling/blob/master/Serve/README.md>. This is a stand-alone way to create and start the service with the crash database loaded. You'll need to do some integration of `docker-compose.yml` and `Dockerfile` to put it on a network, or you could just build the image with this repository and start the service from the resulting image.
